Content:
    code-standards:
        root_dir: ${ROOT_DIR}/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**


Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - css/zapdos.css

Extensions:
    MooseDocs.extensions.navigation:
        name: ComPS Code Standards
        repo: https://github.ncsu.edu/NCSU-ComPS-Group
        menu:
            Getting Started:
                Build The Docs: getting_started/build_the_docs.md
                Using Conda: getting_started/using_conda.md
                Contributing: getting_started/contributing_to_another.md
            Boiler Plate:
                Project: boiler_plate/project.md
                Documentation: boiler_plate/documentation.md
            Standards:
                Tutorial: standards/tutorial.md
                C++: standards/c++.md
                Python: standards/python.md


    MooseDocs.extensions.appsyntax: disable
