name: Generate Personal Website

on:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    # Set up a default shell for all steps
    # See: https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout MOOSE
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Mambaforge3 and MOOSE environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        use-mamba: true
        activate-environment: moose
        environment-file: scripts/conda_environment.yml
    # GitHub-hosted runners are currently limited to 2 cores
    # See: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    - name: Build MOOSE
      run: |
        conda activate moose
        cd moose/test
    - name: Build MooseDocs
      run: |
        cd ../../doc
