name: Generate Personal Website

on:
  push:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    # Set up a default shell for all steps
    # See: https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/site
        # This populates the gh-pages branch with only this update and removes prior history
        force_orphan: true
        user_name: github-actions
        user_email: actions@github.com
        commit_message: "Update personal website based on"
        # The commit SHA that triggered the action is added to the end of the above message.
